version: '3.8'

services:
  db:
    image: postgres:15
    container_name: movieplanet_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=movieplanet
      - POSTGRES_PASSWORD=MoviePlanet
      - POSTGRES_DB=movieplanet
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # AJOUTE CETTE LIGNE CI-DESSOUS :
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: